-- Add workshop settings columns to tenants table
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS address TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS phone VARCHAR(20);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS email VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS owner_name VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS business_hours_open TIME DEFAULT '08:00:00';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS business_hours_close TIME DEFAULT '17:00:00';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS service_tax_rate DECIMAL(5,2) DEFAULT 0.00;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS auto_backup BOOLEAN DEFAULT true;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS email_notifications BOOLEAN DEFAULT true;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS sms_notifications BOOLEAN DEFAULT false;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS invoice_template VARCHAR(50) DEFAULT 'standard';
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS logo_url TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE tenants ADD COLUMN IF NOT EXISTS social_media VARCHAR(255);